### ISSUE TITLE
Unable to build node.js bindings

### ISSUE THREAD

**Issue by brochington** [opencog/link-grammar#1271]
Hello again!

I am unable to build the node.js binding on my M1 Mac Mini. I see the following error when I run `npm install` after building the project (from tarball). 

error messeage
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code 1
npm ERR! path /Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/Library/Caches/node-gyp/17.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/brochstilley/Library/Caches/node-gyp/17.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/brochstilley/Library/Caches/node-gyp/17.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../deps/libffi/src/prep_cif.c:26:10: fatal error: 'ffi.h' file not found
npm ERR! #include <ffi.h>
npm ERR!          ^~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/brochstilley/.volta/tools/image/node/17.3.0/bin/node" "/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
```

Fixes I've attempted: 
- install libffi (`brew install libffi`)
- globally install `node-gyp`
- update my node-gyp common.gypi `MACOSX_DEPLOYMENT_TARGET` flag.

**Comment by linas** [comment]
So, this error:
```
npm ERR! ../deps/libffi/src/prep_cif.c:26:10: fatal error: 'ffi.h' file not found
npm ERR! #include <ffi.h>
npm ERR!          ^~~~~~~
```
 is the root cause of the problems. First wild guess: you might need to say `brew install libffi-dev` or `libffi-devel` or something like that, to get that header file.

But if you do have that header file installed already, then it is somewhere where `gyp` cannot find it. I am utterly clueless for how to tell `gyp` to look for files in unusual directories.  (I know almost nothing at all about node.js. You've have to ask stackexchange about that). Or contact the maintainer... but I see that the maintainer did not put his name anywhere in the code... :-( I'd have to do some git archeology to figure it out. I think it might be  Richard van der Dys  https://github.com/dijs

**Comment by linas** [comment]
ping @dijs per above ... see also #1272

**Comment by brochington** [comment]
I've been able to get a little farther here. My system needed `ffi`, so I `brew install libffi`. brew then gave the following message:

```
libffi is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
```

I did the exports as above, and now when I `npm install`, the error has changed: 

```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code 1
npm ERR! path /Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/brochstilley/Library/Caches/node-gyp/17.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/brochstilley/Library/Caches/node-gyp/17.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/brochstilley/Library/Caches/node-gyp/17.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../deps/libffi/src/prep_cif.c:27:
npm ERR! ../deps/libffi/include/ffi_common.h:17:10: fatal error: 'fficonfig.h' file not found
npm ERR! #include <fficonfig.h>
npm ERR!          ^~~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/brochstilley/.volta/tools/image/node/17.3.0/bin/node" "/Users/brochstilley/.volta/tools/image/node/17.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/brochstilley/Downloads/link-grammar-5.10.2/bindings/node.js/node_modules/ffi
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brochstilley/.npm/_logs/2022-01-06T21_26_43_258Z-debug-0.log
```

I am not sure how to access `fficonfig.h`.

**Comment by linas** [comment]
> libffi is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software

So what happens if you `brew uninstall libffi` ? I would hope that the OS native version should work correctly; and the only requirement would be to adjust  `CPPFLAGS` and maybe `LDFLAGS` so that the OS-native version is found.

**Comment by linas** [comment]
Is this still an issue, or does it now work?

**Comment by linas** [comment]
Closing. Based on issue #1272, I think all problems are resolved. Please open a new issue if not.
