### ISSUE TITLE
Crash in link-generator

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#1276]
I'm getting a crash in `link-generator` with a custom dictionary.
```
link-generator --count=2 --language=dict-en
Program received signal SIGSEGV, Segmentation fault.
../../link-grammar/tokenize/tokenize.c:3012
3012            dn[dict->num_categories-1].right = NULL;
(gdb) print dict->num_categories
0
```
The dataset with this flaw can be found at https://linas.org/datasets/dict-en.tar.bz2

Presumably `num_categories` is zero due to a mis-structured dataset, but I don't understand the problem (yet).  The parser does work, although just barely: there are very few sentences that parse, and I was trying to use link-generator to find out why.

Examples of sentences that parse;
```
V
VI
VI .        % has two parses
God !
```
I was hoping to discover more.

**Comment by linas** [comment]
The `num_categories` is 0 because angle-brackets were used to denote word-classes.  for example, see
```
sqlite3 dict.db
SELECT DISTINCT classname FROM Disjuncts;
```

There should be 5877 of these.  I changed the angle bracket to doublke-curly-brace, and now it prints 
```
# Number of categories: 6
``` 
which sure seems wrong; should be 5877, yes?

Then it crashes
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f5da1b in set_connector_farthest_word (e=0x0, w=w@entry=1, 
    sent_length=3, opts=opts@entry=0x55555555d2a0)
    at ../../link-grammar/connectors.c:60
60              if (e->type == CONNECTOR_type)
(gdb) bt
#0  0x00007ffff7f5da1b in set_connector_farthest_word (e=0x0, w=w@entry=1, 
    sent_length=3, opts=opts@entry=0x55555555d2a0)
    at ../../link-grammar/connectors.c:60
#1  0x00007ffff7f5cfaf in sentence_parse (sent=0x55555b779e00, 
    opts=0x55555555d2a0) at ../../link-grammar/api.c:695
#2  0x000055555555707a in main (argc=<optimized out>, argv=<optimized out>)
    at ../../link-parser/link-generator.c:578
```

**Comment by linas** [comment]
Apparently, the dictionary has categories with no words in them.  That causes some of the failures,  It also has some categories with no expressions in them causing the second failure.

**Comment by linas** [comment]
All of the failing cases have a single apostrophe in the class name.  The sqlite3 engine mis-interprets that; it should have been escaped.   Looks like a case of "little Bobby Tables"

**Comment by linas** [comment]
Pull req #1278 provides a minimal fix that avoids the crash.  However, some kind of safety checks should be added, to detect corrupt dictionaries. The demo dictionary as fine, but that does not mean that future ones might not be corrupted.

**Comment by linas** [comment]
closing; stale bug report.
