### ISSUE TITLE
Apparent Hunspell problem seen in Debian build of 5.12.3  

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1513]
See: https://buildd.debian.org/status/fetch.php?pkg=link-grammar&arch=amd64&ver=5.12.3%7Edfsg-1.1%7Eexp1&stamp=1706921127&raw=0

Configure arguments:
`./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --disable-static --enable-pthreads --with-hunspell-dictdir=/usr/share/hunspell
`

From the output of `configure`:
``` text
checking for hunspell... yes
checking for hunspell.h... yes
```
But the tests that involve spelling fail:
``` text
............................................s...............s.s...F....E..............s.s...................................
======================================================================
ERROR: test_en_spell_word_positions (__main__.IWordPositionTestCase.test_en_spell_word_positions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/bindings/python-examples/./tests.py", line 836, in test_en_spell_word_positions
    linkage_testfile(self, self.d_en, po, 'pos-spell')
  File "/<<PKGBUILDDIR>>/bindings/python-examples/./tests.py", line 1473, in linkage_testfile
    while getwordpos(linkage) != wordpos:
          ^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/bindings/python-examples/./tests.py", line 1397, in getwordpos
    for wi, w in enumerate(lkg.words()):
                           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'words'

======================================================================
FAIL: test_d_spell_guessing_on (__main__.HEnglishLinkageTestCase.test_d_spell_guessing_on)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/bindings/python-examples/./tests.py", line 665, in test_d_spell_guessing_on
    self.assertEqual(list(resultx.words()) if resultx else [],
AssertionError: Lists differ: ['LEF[14 chars], 'love.v', 'going.v', 'to.r', 'shoop[?].v', '.', 'RIGHT-WALL'] != ['LEF[14 chars], 'love.v', 'going.v', 'to.r', 'shop[~].v', '.', 'RIGHT-WALL']

First differing element 5:
'shoop[?].v'
'shop[~].v'

  ['LEFT-WALL',
   'I.p',
   'love.v',
   'going.v',
   'to.r',
-  'shoop[?].v',
?      -  ^

+  'shop[~].v',
?        ^

   '.',
   'RIGHT-WALL']

----------------------------------------------------------------------
Ran 124 tests in 8.222s

FAILED (failures=1, errors=1, skipped=5)

FAIL tests.py (exit status: 1)

============================================================================
Testsuite summary for link-grammar 5.12.3
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

I

**Comment by City-busz** [comment]
I experienced the same on Arch Linux. Installing the en_US Hunspell dictionary into the build environment solves the problem.
