### ISSUE TITLE
Crash in 06391f4515a6f2c2d56bf2a55079a9363f7c1292 (bad free())

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#938]
This cash happens in the current unreleased version at commit 06391f4515a6f2c2d56bf2a55079a9363f7c1292 (current last commit).
It seems it is related to panic.
It happens with the corpus-failure sentence
`I dream of Strathspeld, [...]`
when using the default timeout.
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7ae8895 in __GI_abort () at abort.c:79
#2  0x00007ffff7b419c7 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c4f28c "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7b482cc in malloc_printerr (str=str@entry=0x7ffff7c50f28 "free(): invalid next size (fast)") at malloc.c:5341
#4  0x00007ffff7b49b86 in _int_free (av=0x7ffff7c86c60 <main_arena>, p=0x3c9f640, have_lock=<optimized out>) at malloc.c:4241
#5  0x00007ffff7fa73f5 in string_id_delete (ss=0x2f8b630) at /usr/local/src/link-grammar-devel/master/link-grammar/string-id.c:159
#6  0x00007ffff7f73fcb in sentence_delete (sent=sent@entry=0x14458c0) at /usr/local/src/link-grammar-devel/master/link-grammar/api.c:530
#7  0x0000000000403fb4 in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/link-grammar-devel/master/link-parser/link-parser.c:1052
```

I'm not sure that it is worth fixing or even checking, as in the WIP that I am currently converting to a PR I have reimplemented much of the sentence memory management.

So meanwhile this is only FYI and I will close this issue when the said PR is actually applied.

**Comment by ampli** [comment]
> So meanwhile this is only FYI and I will close this issue when the said PR is actually applied.

Classic-parse memory management reimplemented in PR #981.
This sentence doesn't cause a crash any more.
However, the possible panic state code paths still haven't been checked one by one, still panic mode is to be reimplemented (issue #785).
